#pragma config(Sensor, S1,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S2,     capteurTouchGauche, sensorTouch)
#pragma config(Sensor, S3,     capteurTouchDroite, sensorTouch)
#pragma config(Sensor, S4,     couleur,        sensorColorNxtFULL)
#pragma config(MotorPidSetting,  motorA,  255, 255, 65535, 255, 255,   65535, 65535, 65535)
#pragma config(MotorPidSetting,  motorB,  255, 255, 65535, 255, 255,   65535, 65535, 65535)
#pragma config(MotorPidSetting,  motorC,  255, 255, 65535, 255, 255,   65535, 65535, 65535)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*valeur trouve pour les couleurs:
avec capteur rouge:
noir = en dessous de 330
blanc = au dessus de 550
bleu = entre 400 et 430
vert = entre 400 et 470
rouge = 550
jaune = entre 560 et 600


avec capteur bleu:
noir = en dessous de 430
blanc = au dessus de 500
bleu = entre 370 et 400
vert = entre 335 et 370
rouge = entre 300 335
jaune = entre 360 et 385
avec capteur vert:


noir = en dessous de 375
blanc = au dessus de 580
bleu = entre 375 et 425
vert = entre 425 et 470
rouge = 470 et 500
jaune =  entre 460 et 490


avec capteur full:
noir = 1
blanc = 6
bleu = 2
vert =3
rouge =5
jaune = 4
*/

task main()
{
	int valeurCapteurLumiere = SensorValue(couleur);
	int bla = sensorRaw[couleur];
	while(true)
	{
		valeurCapteurLumiere = SensorValue[couleur];
		bla = sensorRaw[couleur];
		nxtDisplayCenteredTextLine(1, "raw %d", bla);
		nxtDisplayCenteredTextLine(7, "lumiere %d", valeurCapteurLumiere);
		wait1Msec(1000);
	}
}
